# See config.example.yml for documentation.
object_base: orig/RMCP01
object: sys/main.dol
hash: ac7d72448630ade7655fc8bc5fd7a6543cb53a49
symbols: config/RMCP01/symbols.txt
splits: config/RMCP01/splits.txt
# Change this to match the linker verison.
# See config.example.yml for a list.
mw_comment_version: 14

modules:
- object: files/rel/StaticR.rel
  hash: 887bcc076781f5b005cc317a6e3cc8fd5f911300
  symbols: config/RMCP01/module/symbols.txt
  splits: config/RMCP01/module/splits.txt
